#!/usr/bin/env bash
# ===========================================================================
# start-graphiti.sh
#
# Start the Graphiti MCP server (FalkorDB combined container).
# Creates the .env file if missing and runs docker compose.
#
# Usage:
#   ./scripts/start-graphiti.sh              # start in foreground
#   ./scripts/start-graphiti.sh --detach     # start in background
#   ./scripts/start-graphiti.sh --stop       # stop the server
#   ./scripts/start-graphiti.sh --status     # check health
#
# Prerequisites:
#   - Docker and Docker Compose
#   - OPENAI_API_KEY env var (or will prompt)
#   - Graphiti repo cloned at $GRAPHITI_DIR (default: ~/MachinezDesign/graphiti)
# ===========================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

GRAPHITI_DIR="${GRAPHITI_DIR:-$HOME/MachinezDesign/graphiti}"
MCP_DIR="$GRAPHITI_DIR/mcp_server"
# Relative compose path — must be run from $MCP_DIR (as Graphiti README says)
COMPOSE_REL="docker/docker-compose.yml"
COMPOSE_ABS="$MCP_DIR/$COMPOSE_REL"

if [ ! -f "$COMPOSE_ABS" ]; then
  echo "ERROR: Compose file not found at $COMPOSE_ABS"
  echo ""
  echo "Clone graphiti first:"
  echo "  git clone https://github.com/getzep/graphiti.git $GRAPHITI_DIR"
  exit 1
fi

# Helper: run docker compose from the mcp_server directory so that
# env_file: path: ../.env resolves correctly (../ = mcp_server/).
dc() {
  (cd "$MCP_DIR" && docker compose -f "$COMPOSE_REL" "$@")
}

# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------

case "${1:---detach}" in
  --stop)
    echo "==> Stopping Graphiti MCP server..."
    dc down
    echo "    Stopped."
    exit 0
    ;;

  --status)
    echo "==> Graphiti MCP server status:"
    dc ps 2>/dev/null || true
    echo ""
    echo -n "    MCP endpoint: "
    if curl -sfL --max-time 3 -X POST \
      -H "Content-Type: application/json" \
      -H "Accept: application/json, text/event-stream" \
      -d '{"jsonrpc":"2.0","method":"initialize","params":{"protocolVersion":"2025-03-26","capabilities":{},"clientInfo":{"name":"test","version":"1.0.0"}},"id":1}' \
      http://localhost:8000/mcp > /dev/null 2>&1; then
      echo "HEALTHY"
    else
      echo "NOT RESPONDING"
    fi
    exit 0
    ;;

  --help|-h)
    sed -n '2,/^# ====/{ /^# /s/^# //p }' "$0"
    exit 0
    ;;
esac

# ---------------------------------------------------------------------------
# Ensure .env file exists with OPENAI_API_KEY
# ---------------------------------------------------------------------------

ENV_FILE="$MCP_DIR/.env"

if [ ! -f "$ENV_FILE" ]; then
  echo "==> No .env file found at $ENV_FILE"

  if [ -n "${OPENAI_API_KEY:-}" ]; then
    echo "    Using OPENAI_API_KEY from environment."
    API_KEY="$OPENAI_API_KEY"
  else
    echo ""
    echo "    The Graphiti MCP server needs an OpenAI API key for"
    echo "    entity extraction and embeddings."
    echo ""
    read -rp "    Enter your OPENAI_API_KEY: " API_KEY
    if [ -z "$API_KEY" ]; then
      echo "    ERROR: API key is required."
      exit 1
    fi
  fi

  cat > "$ENV_FILE" <<EOF
# Graphiti MCP Server - generated by start-graphiti.sh
OPENAI_API_KEY=$API_KEY
MODEL_NAME=gpt-4.1-mini
SEMAPHORE_LIMIT=10
EOF

  echo "    Created $ENV_FILE"
fi

# ---------------------------------------------------------------------------
# Start the server
# ---------------------------------------------------------------------------

DETACH_FLAG=""
if [ "${1:-}" = "--detach" ] || [ "${1:-}" = "-d" ]; then
  DETACH_FLAG="-d"
fi

echo "==> Starting Graphiti MCP server (FalkorDB combined container)..."
echo "    Compose file: $COMPOSE_ABS"
echo "    Working dir:  $MCP_DIR"
echo "    Endpoint:     http://localhost:8000/mcp"
echo ""

dc up $DETACH_FLAG

if [ -n "$DETACH_FLAG" ]; then
  echo ""
  echo "==> Server starting in background. Check status with:"
  echo "    $0 --status"
  echo ""
  echo "    Waiting for health check..."
  for i in $(seq 1 60); do
    if curl -sfL --max-time 2 -X POST \
      -H "Content-Type: application/json" \
      -H "Accept: application/json, text/event-stream" \
      -d '{"jsonrpc":"2.0","method":"initialize","params":{"protocolVersion":"2025-03-26","capabilities":{},"clientInfo":{"name":"test","version":"1.0.0"}},"id":1}' \
      http://localhost:8000/mcp > /dev/null 2>&1; then
      echo "    MCP server is READY at http://localhost:8000/mcp"
      exit 0
    fi
    sleep 1
  done
  echo "    WARNING: Server did not become healthy within 60s."
  echo "    Check logs: cd $MCP_DIR && docker compose -f $COMPOSE_REL logs"
fi
